### ISSUE TITLE
Drag ID-ed objects via jquery

### ISSUE THREAD

**Issue by rubyFeedback** [sachinchoolur/replace-jquery#6]
Could you mention whether dragging objects via jquery is handled by replace-jquery as well? I use that feature
of jquery primarily on many images. I like being able to shift the image a bit. I know there is more-than-one-way
to do it but I settled for jquery, so knowing that it is easily possible in vanilla js and replace-jquery suggesting
the alternative would be useful IMO. Perhaps the main README could mention that.

It's jquery-ui though so not sure this applies to the project as well (not sure whether jquery-ui is handled by
replace-jquery or not)

See here how that code looks for jquery: https://www.javatpoint.com/jquery-ui-draggable

**Comment by sachinchoolur** [comment]
Hey @rubyFeedback,

Jquery Ui is a collection of libraries built on top of the jQuery library. It is not handled by replace-jQuery. 

I just ran `replace-jQuery` on jQuery UI and it used more than 70 jQuery functions including functions with native equivalents.

If you want to get rid of jQuery-ui-draggable, I'd recommend you to use any tiny draggable JavaScript libraries or do it by using plain JavaScript
