### ISSUE TITLE
replace-jQuery: command not found

### ISSUE THREAD

**Issue by krystiangorecki** [sachinchoolur/replace-jquery#8]
I'm following this quick start guide: https://github.com/sachinchoolur/replace-jquery#installation-and-usage
but it fails on `replace-jQuery src/sample.js out.js` with error:
`replace-jQuery: command not found`
but it works when I replace `Q` with `q`:

![Screenshot from 2021-09-17 18-31-45](https://user-images.githubusercontent.com/10375973/133823014-cf9389ff-5a71-47d6-9ce1-a435d9cd09bb.png)

Is that case-sensitivity issue related to my system or is your tutorial broken?

**Comment by sachinchoolur** [comment]
Thank you for pointing this out.
